collaborationFactory/cplace-npm-tools

src/util.ts
=> Fix newline replacement and trim correctly

src/cli.ts, src/commands/e2e/E2E.ts, src/commands/e2e/E2EEnvTemplate.ts
Companion for https://github.com/collaborationFactory/cplace/pull/2569
=> Allow configuration of e2e token via parameter

src/cli.ts, src/commands/e2e/ConfigTemplate.ts, src/commands/e2e/E2E.ts, src/commands/e2e/WdioConfigGenerator.ts
jUnit Test Reports capability added, useful to show Test Results in Jenkins
=> junit capability added

src/cli.ts
Fixed typos in the cplace cli help
=> Fixed typo in cplace-cli help

src/commands/repos/UpdateRepos.ts, src/git/Repository.ts
=> Improved Error Message if Remote Branch doesnt exist

package-lock.json, package.json, src/cli.ts
PR to add updat-notifier to cplace-cli
=> added update notification on every startup

src/commands/e2e/E2E.ts
=> Allow case insensitive flags

src/commands/e2e/ConfigTemplate.ts
exchanged jasmine by mocha in wdio configuration
=> PFM-ISSUE-2994 exchanged jasmine by mocha in wdio configuration

src/commands/e2e/ConfigTemplate.ts, src/commands/e2e/WdioConfigGenerator.ts
adds plugin detection before test execution
=> PFM ISSUE 2992 add functionality to skip tests for e2e tests

src/commands/e2e/E2E.ts
changelog: cplace-cli: added filtering of plugins on criteria if tests are specified  [PR cplace-npm-tools #41]
solves #40
=> added filtering of plugins on criteria if tests are specified

src/commands/e2e/ConfigTemplate.ts, src/commands/e2e/E2E.ts, src/commands/e2e/WdioConfigGenerator.ts
Resolves [PFM-ISSUE-3684](https://base.cplace.io/pages/o61l6mptqvyya5w7cci3wgzzx/PFM-ISSUE-3684-Enable-listing-of-Plugins-for-Multitenancy-in-cplace-cli-e2e-functionality)
`changelog: Platform Development: Enable listing of Plugins for Multitenancy in cplace-cli e2e functionality [PFM-ISSUE-3684, PR cplace#2953]`
=> PFM-ISSUE-3684 - Enable listing of Plugins for Multitenancy in cplace-cli e2e functionality

.npmignore, package-lock.json, package.json, src/commands/release-notes/ReleaseNotesMessagesFile.test.ts, tsconfig.json
Resolves [PFM-ISSUE-4061](https://base.cplace.io/pages/krep1o2mdouujp7rvia1ahyrh/PFM-ISSUE-4061-Add-unit-testing-capabilities-to-cplace-cli)
Included Jest as well as ts-jest and typings to write unit tests easily.
`changelog: cplace-cli Development: [PFM-ISSUE-4061]: Added Jest and ts-jest to enable writing unit tests [cplace-npm-tools#44]`
=> PFM-ISSUE-4061: Add unit testing capabilities with Jest

src/commands/e2e/ConfigTemplate.ts
Resolves [PFM-ISSUE-4641](https://base.cplace.io/pages/rcpbs26cznarkog8akw1g2e03/PFM-ISSUE-4641-Proper-Error-handling-in-cplace-cli-e2e-functionality-if-cplace-is-not-yet-ready)
`changelog: Platform Development: [PFM-ISSUE-4641] Fix: improved error handling and message in e2e plugin detection [PR cplace#52]`
**Checklist:**
=> PFM-ISSUE-4641 improved error handling and message in e2e plugin detection

src/cli.ts, src/commands/repos/UpdateRepos.ts, src/commands/repos/models.ts, src/git/Repository.ts
Resolves [PFM-ISSUE-3903](https://base.cplace.io/pages/hgt1nkz2xco3w3ymsn4jdh1ew/PFM-ISSUE-3903-Add-git-tag-support)
`changelog: Platform Development: [PFM-ISSUE-3903] Fix: added git tag support [PR cplace#53]`
**Checklist:**
=> PFM-ISSUE-3903 added git tag support

src/commands/e2e/ConfigTemplate.ts
replacing the screenshot name from `test.fullTitle` to `test.title`
=> PFM-ISSUE-4620 Shorten the name of e2e screenshot

src/cli.ts, src/commands/CommandRunner.ts, src/commands/repos/AbstractReposCommand.ts, src/commands/repos/Repos.ts, src/commands/repos/UpdateRepos.ts, src/git/Repository.ts, src/promiseAllSettled.ts
Fixes #50 
`changelog: Fix git locks left behind when repos -u aborts due to unclean working copy [Issue cplace-npm-tools#50, PR cplace-npm-tools#57]`
=> Issue #50 - repos update leaves lock

src/commands/e2e/E2E.ts, src/commands/e2e/TestRunner.ts, src/commands/e2e/util.ts
Fixes #55 
changelog: bugfix for wrong error code on specified specs parameter [Issue cplace-npm-tools#55, PR cplace-npm-tools#60]
=> issue #55 bugfix for wrong error code on specified specs parameter

.github/workflows/continuous-integration.yml, README.md
=> Add workflow to run all tests

src/cli.ts, src/commands/e2e/E2E.test.ts, src/commands/e2e/E2E.ts, src/commands/e2e/WdioConfigGenerator.ts, src/commands/e2e/WdioConfigTemplate.ts
- Added wdio-image-comparison-service
- Added devtools service
- Added logLevel configuration
=> PFM-ISSUE-5512  Added new wdio services

README.md, package.json, src/cli.ts, src/commands/repos/AbstractReposCommand.ts, src/commands/repos/CloneRepos.ts, src/git/Repository.ts
Resolves [PFM-ISSUE-7248](https://base.cplace.io/pages/wpslc6iselmpuidba6qon4kf2/PFM-ISSUE-7248-Shallow-Clones-for-Parent-Repos)
Manual test report and measures are found in the PFM issue.
=> PFM-ISSUE-7248: Shallow Clones for Parent Repos

package-lock.json, package.json, src/commands/flow/ReleaseNumber.ts, src/commands/flow/SplitRepository.ts, src/commands/flow/Upmerge.ts, src/commands/visualize/VisualizeCommand.ts, src/test/ReleaseNumber.test.ts, src/test/e2e/E2E.test.ts, src/test/flow/ReleaseNumber.test.ts, src/test/helpers/GradleBuild.test.ts, src/test/helpers/repositories.ts, src/test/release-notes/ReleaseNotesMessagesFile.test.ts, src/test/repos/DependencyManagement.test.ts, src/test/repos/GradleDependencyManagement.test.ts, src/test/repos/IdeaDependencyManagement.test.ts
[PFM-ISSUE-10209](https://base.cplace.io/pages/j1o2rgkkk1vd23u7fcyst244u/PFM-ISSUE-10209-Support-main-branch-in-the-cplace-cli#id_wsrqdlqi9cus7fztqfsfa3gnz=cf.cplace.cfactoryPlatform.overview)
=> PFM-ISSUE-10209: Support main branch in the cplace-cli

package-lock.json, package.json, src/commands/release-notes/GenerateReleaseNotes.ts, src/git/models.ts, test/release-notes/GenerateReleaseNotes.test.ts
Resolves [PFM-ISSUE-11020](https://base.cplace.io/pages/rc1peqfvl3sh8b4nriri85a5q/PFM-ISSUE-11020-Alphabetically-sort-the-release-notes-by-the-squad-name#id_wsrqdlqi9cus7fztqfsfa3gnz=cf.cplace.cfactoryPlatform.overview)
=> PFM-ISSUE-11020 alphabetically sort the release notes by the squad name

README.md, package-lock.json, package.json, src/Global.ts, src/cli.ts, src/commands/repos/AbstractReposCommand.ts, src/commands/repos/CloneRepos.ts, src/commands/repos/UpdateRepos.ts, src/commands/repos/WriteRepos.ts, src/commands/repos/models.ts, src/git/Repository.ts, test/helpers/remoteRepositories.ts, test/repos/CloneRepos.test.ts, test/repos/UpdateRepos.test.ts, test/repos/WriteRepos.test.ts
Resolves [PFM-ISSUE-11622](https://base.cplace.io/pages/mpxzbnjc5gtcmcim37277eszz/PFM-ISSUE-11622-cplace-cli-improve-cloning-and-updating-repos)
=> PFM-ISSUE-11622: cplace-cli: improve cloning and updating repos

README.md, package-lock.json, package.json, src/cli.ts, src/commands/repos/WriteRepos.ts
Resolves [PFM-ISSUE-11776](https://base.cplace.io/pages/g2i3yuu428bokq8vqtblqcjdr/PFM-ISSUE-11776-cplace-cli-don-t-write-commit-hash-the-using-latest-tag)
does not update to commit if without --freeze
=> PFM-ISSUE-11776: cplace-cli: don't write commit hash the using --latest-tag

package-lock.json, package.json, src/git/Repository.ts, test/git/Repository.test.ts
Resolves [PFM-ISSUE-12413](https://base.cplace.io/pages/vgoc7obflhq5yvnp4lahy2cfp/PFM-ISSUE-12413-cplace-cli-don-t-fail-if-remote-url-origin-does-not-exists)
=> PFM-ISSUE-12413 - cplace-cli: don't fail if remote url 'origin' does not exists

package-lock.json, package.json, src/git/Repository.ts, test/git/Repository.test.ts
Resolves [PFM-ISSUE-12413](https://base.cplace.io/pages/vgoc7obflhq5yvnp4lahy2cfp/PFM-ISSUE-12413-cplace-cli-don-t-fail-if-remote-url-origin-does-not-exists)
Upmerge of #124
=> Upmerge: PFM-ISSUE-12413 - cplace-cli: don't fail if remote url 'origin' does not exists

README.md, src/cli.ts, src/commands/repos/AbstractReposCommand.ts, src/commands/repos/CloneRepos.ts, src/commands/repos/UpdateRepos.ts, src/git/Repository.ts, src/promiseAllSettled.ts, test/helpers/remoteRepositories.ts, test/helpers/repositories.ts, test/promiseAllSettled.test.ts, test/repos/CloneRepos.test.ts
=> Cherry pick/1.0/pfm task 3600 and pfm issue 12941

package-lock.json, package.json, src/git/Repository.ts, test/git/Repository.test.ts
Resolves [PFM-ISSUE-24725](https://base.cplace.io/pages/boglz74stphkjqiyylrdq2n1t/PFM-ISSUE-24725-cplace-cli-adjust-for-using-RC-tags)
=> PFM-ISSUE-24725: cplace-cli: adjust for using RC tags

package-lock.json, package.json, src/commands/repos/ValidateBranches.ts, test/repos/ValidateBranches.test.ts
Resolves [PFM-ISSUE-24917](https://base.cplace.io/pages/z6gua9ts7ot0u0wa0dzjw7ygh/PFM-ISSUE-24917-cplace-cli-improve-repos-validateBranches-command)
=> PFM-ISSUE-24917 - cplace-cli: improve repos --validateBranches command

package-lock.json, package.json, src/git/Repository.ts
Resolves [PFM-ISSUE-27433](https://base.cplace.io/pages/0pfb30ezw1yvdja6re7oegey0/PFM-ISSUE-27433-cplace-cli-reduce-error-logging-for-the-upmerge-flow)
=> PFM-ISSUE-27433 - cplace-cli: reduce error logging for the upmerge flow

package-lock.json, package.json, src/git/Repository.ts
Resolves [PFM-ISSUE-28139 ](https://base.cplace.io/pages/bv0rfzl82nwlat3lf0sax11ms/PFM-ISSUE-28139-cplace-cli-Fix-Placeholder-Replacement-in-logging#id_wsrqdlqi9cus7fztqfsfa3gnz=newOverview)
=> PFM-ISSUE-28139 - cplace-cli: Fix Placeholder Replacement in logging

.github/workflows/continuous-integration.yml, src/cli.ts, src/commands/CommandRunner.ts
Resolves [PFM-ISSUE-29601](https://base.cplace.io/pages/5j203cnwcrl866rktt43nv9yd/PFM-ISSUE-29601-cplace-cli-unknown-commands-not-handled-correctly)
=> PFM-ISSUE-29601: unknown commands not handled correctly
